### PR TITLE
changed warning for convergence

### PR DESCRIPTION
**Pull request by eweine**
@pcarbo I've received a few questions from people using fastglmpca about what to do when fastglmpca hasn't converged. Based on the new experiments in our paper, I think it's reasonable to suggest that it _might_ be okay to run clustering on a model that has not fully converged. What do you think?

### CODE REVIEW

**Comment by pcarbo** [comment]
@eweine Toning down the message is not a bad a idea; for example, we could say something like, "Note that the specified convergence criterion was not satisified within X iterations." We could also convert it from warning to a message. We might want to complement this with a message that indicates with the convergence criterion was sastified, e.g., "Stopping at iteration X because the convergence criterion was met."

I don't see a need to mention anything specifically about clustering — clustering is an entirely independent step. The larger question about when the results are "good enough" does not have a straightforward answer; the answer to this question will depend on the data set. The user will have to use their own judgement.

**Comment by eweine** [comment]
Ok @pcarbo I took your advice above.

**Comment by pcarbo** [comment]
@eweine That looks good, except that the convention in R is to use `message()` (analogous to `warning()`).

**Comment by eweine** [comment]
> @eweine That looks good, except that the convention in R is to use `message()` (analogous to `warning()`).

Ok, I changed it to a message.

**Pull request merged**
